services:
  nextjs-app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - indoipo-network

  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_DB: indoipo
      POSTGRES_USER: indoipo
      POSTGRES_PASSWORD: indoipo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - indoipo-network

networks:
  indoipo-network:
volumes:
  postgres-data:
