services:
  nextjs-app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: indoipo
      POSTGRES_USER: indoipo
      POSTGRES_PASSWORD: indoipo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
volumes:
  postgres-data:
