import Head from "next/head";
import prisma from "@/lib/prisma";
import CompanyComponent from "@/app/companies/[ticker]/Company";
import {notFound} from "next/navigation";

export default async function Company({params}) {
    let company = await prisma.company.findFirst({
        where: {
            ticker: params.ticker,
        },
        include: {
            subsector: {
                include: {
                    sector: true
                }
            },
            financials: {
                orderBy:  {
                    date_end: 'desc'
                }
            }
        }
    });

    if (!company) {
        notFound()
    }

    company = JSON.parse(JSON.stringify(company, (key, value) =>
        typeof value === 'bigint'
            ? value.toString()
            : value
    ));

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <CompanyComponent company={company}></CompanyComponent>
        </>
    );
}
