import Head from "next/head";
import prisma from "@/lib/prisma";
import CompanyComponent from "@/app/companies/[ticker]/Company";

export async function Company({params}) {
    let company = await prisma.company.findFirst({
        where: {
            ticker: params.ticker,
        },
        include: {
            financials: true
        }
    });
    company = JSON.parse(JSON.stringify(company, (key, value) =>
        typeof value === 'bigint'
            ? value.toString()
            : value
    ));

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <CompanyComponent company={company}></CompanyComponent>
        </>
    );
}

export default Company;