async function seedCompanies(prisma) {
    await prisma.company.upsert({
        where: { id: 1 },
        update: {},
        create: {
            name: 'PT Nusantara Sejahtera Raya Tbk',
            description: 'Perseroan dan Entitas Anak (selanjutnya disebut "Cinema XXI") berkedudukan di Jakarta Pusat, didirikan pada tahun 1988 berdasarkan peraturan perundang-undangan yang berlaku di Negara Republik Indonesia, dengan nama PT Subentra Nusantara berdasarkan Akta Pendirian No. 67 tanggal 7 Juni 1988 yang ditandai dengan pembukaan Studio 21, multipleks modern pertama di Indonesia. Perseroan merupakan perusahaan yang fokus dalam pemutaran film dan penyediaan F&B untuk memberikan pengalaman hiburan yang berkualitas tinggi.',
            ticker: 'CNMA',
            img: 'CNMA.png',
            address: 'Jl. KH Wahid Hasyim No.96-A Jakarta Pusat 10340 ',
            bidang_usaha: 'Bioskop & Restoran',
            website: 'https://www.cinema21.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=246&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=246&type=summary',
            e_ipo_url: 'https://e-ipo.co.id/id/ipo/246/cnma-pt-nusantara-sejahtera-raya-tbk',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=246',
            low_price: 270,
            high_price: 288,
            waran_numerator: 100,
            waran_denominator: 275,
            offered_shares: 8335000000,
            outstanding_shares: 83345000000,
            date_awal_start: new Date("2023-07-16"),
            date_awal_end: new Date("2023-07-18"),
            date_umum_start: new Date("2023-07-19"),
            date_umum_end: new Date("2023-07-20"),
            date_penjatahan: new Date("2023-07-21"),
            date_distribusi: new Date("2023-07-22"),
            date_ipo: new Date("2023-07-23"),
            subsector_id: 1,
        },
    })
    await prisma.company.upsert({
        where: { id: 2 },
        update: {},
        create: {
            name: 'PT Barito Renewables Energy Tbk',
            description: 'PT Barito Renewables Energy Tbk (atau disebut juga Barito Renewables atau Perusahaan) adalah perusahaan induk berbasis Indonesia yang merupakan bagian dari Grup Barito Pacific. Fokus utama Barito Renewables adalah menyediakan energi yang lebih bersih dan berkontribusi pada upaya Indonesia menuju Net Zero Emission (NZE). Awalnya, perusahaan ini memulai operasinya melalui Star Energy Geothermal Group, yang merupakan pemain terkemuka dalam produksi listrik tenaga panas bumi.\n' +
                '\n' +
                'Saat ini, Grup Perusahaan mengelola tiga aset panas bumi yang berlokasi di Jawa Barat dengan total kapasitas terpasang sekitar 886MW. Hal ini mencerminkan sekitar 38% pangsa pasar di Indonesia./2023) dan tanggal 24 Juli 2023 (Akta No. 084/2023). Perusahaan berfokus pada bidang penjualan GPS Pelacak Kendaraan dan menyediakan layanan yang mencakup penjualan perangkat keras dan perangkat lunak untuk produk Internet of Things (IoT) transportasi darat, seperti gps tracker. Dengan konsumen utama dari berbagai sektor, termasuk perusahaan logistik, rental, pembiayaan, korporasi, dan individu yang ingin melacak kendaraan mereka, Perusahaan menjalankan layanan pelanggan 24 jam dengan dukungan teknis yang tersebar di berbagai kota di Indonesia. Fox Logger, sebagai solusi pelacakan yang inovatif, menjadi produk andalan perusahaan ini dengan kemampuan menerima data dari berbagai merek GPS Car Tracker dengan Call Center 24 jam. Dengan keunggulan kompetitif seperti sertifikasi internasional, kemampuan penyesuaian fitur, dan dukungan teknis yang handal, Perusahaan terus berkembang dalam industri pelacakan dan manajemen kendaraan.',
            ticker: 'BREN',
            img: 'BREN.png',
            address: 'Wisma Barito Pacific II, Lantai 23, Jl. Let. Jend. S. Parman Kav. 60, RT 010, RW 005, Slipi, Palmerah, Jakarta 11410, Indonesia',
            bidang_usaha: 'Aktvitas Perusahaan Holding',
            website: 'https://www.baritorenewables.co.id/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=266&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=266&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=266',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/266/bren-pt-barito-renewables-energy-tbk',
            low_price: 670,
            high_price: 780,
            offered_shares: 4500000000,
            outstanding_shares: 134271220000,
            date_awal_start: new Date("2023-09-18"),
            date_awal_end: new Date("2023-09-25"),
            date_umum_start: new Date("2023-10-02"),
            date_umum_end: new Date("2023-10-04"),
            date_penjatahan: new Date("2023-10-04"),
            date_distribusi: new Date("2023-10-05"),
            date_ipo: new Date("2023-10-06"),
            subsector_id: 7,
        },
    })
    await prisma.company.upsert({
        where: { id: 3 },
        update: {},
        create: {
            name: 'PT Sumber Sinergi Makmur Tbk',
            description: 'PT Sumber Sinergi Makmur, yang berkantor pusat di Jakarta Pusat, didirikan pada tanggal 19 Mei 2015 berdasarkan Akta Pendirian No. 88 yang dibuat di hadapan seorang notaris di Jakarta Pusat. Perusahaan ini memperoleh status badan hukum pada tanggal 28 Mei 2015 berdasarkan Surat Keputusan Menkumham No. AHU-2440801.01.01.Tahun 2015. Selama perjalanannya, Anggaran Dasar Perusahaan telah mengalami beberapa kali perubahan, yang terakhir terjadi pada tanggal 25 Mei 2023 (Akta No. 57/2023) dan tanggal 24 Juli 2023 (Akta No. 084/2023). Perusahaan berfokus pada bidang penjualan GPS Pelacak Kendaraan dan menyediakan layanan yang mencakup penjualan perangkat keras dan perangkat lunak untuk produk Internet of Things (IoT) transportasi darat, seperti gps tracker. Dengan konsumen utama dari berbagai sektor, termasuk perusahaan logistik, rental, pembiayaan, korporasi, dan individu yang ingin melacak kendaraan mereka, Perusahaan menjalankan layanan pelanggan 24 jam dengan dukungan teknis yang tersebar di berbagai kota di Indonesia. Fox Logger, sebagai solusi pelacakan yang inovatif, menjadi produk andalan perusahaan ini dengan kemampuan menerima data dari berbagai merek GPS Car Tracker dengan Call Center 24 jam. Dengan keunggulan kompetitif seperti sertifikasi internasional, kemampuan penyesuaian fitur, dan dukungan teknis yang handal, Perusahaan terus berkembang dalam industri pelacakan dan manajemen kendaraan.',
            ticker: 'IOTF',
            img: 'IOTF.png',
            address: 'Fox Logger Tower Jl. Cideng Barat nomor 31A, RT. 003/RW. 011, Kelurahan Cideng, Kecamatan Gambir, Jakarta Pusat 10150',
            bidang_usaha: 'Distributor dan Instalasi Perangkat Global Positioning System (GPS) untuk Otomotif dan Logistik',
            website: 'https://www.foxlogger.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=265&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=265&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=265',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/265/iotf-pt-sumber-sinergi-makmur-tbk',
            low_price: 100,
            high_price: 120,
            offered_shares: 1100000000,
            outstanding_shares: 5280000000,
            waran_numerator: 1,
            waran_denominator: 1,
            exercise_price: 130,
            date_awal_start: new Date("2023-09-14"),
            date_awal_end: new Date("2023-09-19"),
            date_umum_start: new Date("2023-10-2"),
            date_umum_end: new Date("2023-10-5"),
            date_penjatahan: new Date("2023-10-5"),
            date_distribusi: new Date("2023-10-6"),
            date_ipo: new Date("2023-10-9"),
            subsector_id: 3,
        },
    })
    await prisma.company.upsert({
        where: { id: 4 },
        update: {},
        create: {
            name: 'PT Anugerah Spareparts Sejahtera Tbk',
            description: 'PT Anugerah Spareparts Sejahtera adalah perusahaan yang didirikan berdasarkan Akta Pendirian Perseroan Terbatas pada tanggal 10 September 2015 di Kota Cirebon. Mereka telah mendapatkan pengesahan resmi dari Menteri Hukum dan Hak Asasi Manusia Republik Indonesia. Sejak pendirian hingga saat ini, Anggaran Dasar perusahaan telah mengalami beberapa perubahan, yang terakhir dilakukan pada tanggal 28 April 2023. Perusahaan ini memiliki domisili di Kabupaten Cirebon dan kantor pusatnya berada di Jalan Soekarno Hatta Nomor 134. Mereka bergerak dalam industri suku cadang dan aksesori kendaraan bermotor roda empat atau lebih, perdagangan besar suku cadang dan aksesori mobil, serta perdagangan besar bahan konstruksi dari kayu. Saat ini, kegiatan utama perusahaan berfokus pada industri suku cadang dan aksesori kendaraan bermotor roda empat atau lebih serta perdagangan besar suku cadang dan aksesori mobil.',
            ticker: 'AEGS',
            img: 'AEGS.jpg',
            address: 'Jalan Soekarno Hatta No. 134, Losari Kidul, Losari, Kab. Cirebon, Jawa Barat 45192',
            bidang_usaha: 'Industri Filter Kendaraan Bermotor yaitu Filter Oli dan Filter Bahan Bakar, serta Perdagangan Filter',
            website: 'https://www.aegisfilter.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=262&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=262&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=262',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/262/aegs-pt-anugerah-spareparts-sejahtera-tbk',
            low_price: 90,
            high_price: 100,
            final_price: 100,
            offered_shares: 400000000,
            outstanding_shares: 1006000000,
            waran_numerator: 4,
            waran_denominator: 1,
            exercise_price: 90,
            date_awal_start: new Date("2023-08-22"),
            date_awal_end: new Date("2023-08-24"),
            date_umum_start: new Date("2023-09-04"),
            date_umum_end: new Date("2023-09-07"),
            date_penjatahan: new Date("2023-09-07"),
            date_distribusi: new Date("2023-09-08"),
            date_ipo: new Date("2023-09-11"),
            subsector_id: 4,
        },
    })
    await prisma.company.upsert({
        where: { id: 5 },
        update: {},
        create: {
            name: 'PT Kokoh Exa Nusantara Tbk',
            description: 'PT Kokoh Exa Nusantara adalah perusahaan di bidang konstruksi dan properti yang didirikan pada tahun 2019 di Kabupaten Bangkalan, Jawa Timur. Mereka fokus pada pengembangan proyek perumahan Kokoh City, dengan penjualan rumah subsidi untuk Masyarakat Berpenghasilan Rendah (MBR) dan rumah komersial konsep "Kota Mandiri." Kokoh City terletak sekitar 15 km dari pusat Surabaya dan merupakan bagian dari GERBANG KERTASUSILA, wilayah penyanggah Surabaya.\n' +
                '\n' +
                'Perusahaan ini memiliki dukungan teknologi pembuatan dinding rumah yang dipatenkan dari PT Kokoh Anugerah Nusantara, pemegang saham mereka. PT Kokoh Anugerah Nusantara telah berpengalaman di industri properti, real estat, dan konstruksi sejak 2015.\n' +
                '\n' +
                'PT Kokoh Exa Nusantara juga memiliki peran penting dalam penyaluran Fasilitas Likuiditas Pembiayaan Perumahan (FLPP) untuk rumah tapak MBR di Provinsi Jawa Timur, dan merupakan penyumbang terbesar di Kabupaten Bangkalan, Madura menurut BP Tapera pada tahun 2022.',
            ticker: 'KOCI',
            img: 'KOCI.jpg',
            address: 'Jl. Raya Sukolilo, Tebul, Kwanyar, Bangkalan - 69163',
            bidang_usaha: 'Konstruksi dan Real Estat',
            website: 'https://www.kokohcity.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=264&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=264&type=summary',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/264/koci-pt-kokoh-exa-nusantara-tbk',
            low_price: 120,
            high_price: 160,
            offered_shares: 450000000,
            outstanding_shares: 4415590000,
            waran_numerator: 1,
            waran_denominator: 1,
            date_awal_start: new Date("2023-09-07"),
            date_awal_end: new Date("2023-09-12"),
            date_umum_start: new Date("2023-09-27"),
            date_umum_end: new Date("2023-10-04"),
            date_penjatahan: new Date("2023-10-05"),
            date_distribusi: new Date("2023-10-09"),
            date_ipo: new Date("2023-10-10"),
            subsector_id: 5,
        },
    })
}

module.exports = { seedCompanies }