async function seedCompanies(prisma) {
    await prisma.company.upsert({
        where: { id: 1 },
        update: {},
        create: {
            name: 'PT Nusantara Sejahtera Raya Tbk',
            description: 'Perseroan dan Entitas Anak (selanjutnya disebut "Cinema XXI") berkedudukan di Jakarta Pusat, didirikan pada tahun 1988 berdasarkan peraturan perundang-undangan yang berlaku di Negara Republik Indonesia, dengan nama PT Subentra Nusantara berdasarkan Akta Pendirian No. 67 tanggal 7 Juni 1988 yang ditandai dengan pembukaan Studio 21, multipleks modern pertama di Indonesia. Perseroan merupakan perusahaan yang fokus dalam pemutaran film dan penyediaan F&B untuk memberikan pengalaman hiburan yang berkualitas tinggi.',
            ticker: 'CNMA',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/CNMA.webp',
            address: 'Jl. KH Wahid Hasyim No.96-A Jakarta Pusat 10340',
            bidang_usaha: 'Bioskop & Restoran',
            website: 'https://www.cinema21.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=246&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=246&type=summary',
            e_ipo_url: 'https://e-ipo.co.id/id/ipo/246/cnma-pt-nusantara-sejahtera-raya-tbk',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=246',
            low_price: 270,
            high_price: 288,
            // final_price: 270,
            waran_numerator: 100,
            waran_denominator: 275,
            offered_shares: 8335000000,
            outstanding_shares: 83345000000,
            date_awal_start: new Date("2023-07-16"),
            date_awal_end: new Date("2023-07-18"),
            date_umum_start: new Date("2023-07-19"),
            date_umum_end: new Date("2023-07-20"),
            date_penjatahan: new Date("2023-07-21"),
            date_distribusi: new Date("2023-07-22"),
            date_ipo: new Date("2023-07-23"),
            subsector_id: 1,
        },
    })
    await prisma.company.upsert({
        where: { id: 2 },
        update: {},
        create: {
            name: 'PT Barito Renewables Energy Tbk',
            description: 'PT Barito Renewables Energy Tbk (atau disebut juga Barito Renewables atau Perusahaan) adalah perusahaan induk berbasis Indonesia yang merupakan bagian dari Grup Barito Pacific. Fokus utama Barito Renewables adalah menyediakan energi yang lebih bersih dan berkontribusi pada upaya Indonesia menuju Net Zero Emission (NZE). Awalnya, perusahaan ini memulai operasinya melalui Star Energy Geothermal Group, yang merupakan pemain terkemuka dalam produksi listrik tenaga panas bumi.\n' +
                '\n' +
                'Saat ini, Grup Perusahaan mengelola tiga aset panas bumi yang berlokasi di Jawa Barat dengan total kapasitas terpasang sekitar 886MW. Hal ini mencerminkan sekitar 38% pangsa pasar di Indonesia./2023) dan tanggal 24 Juli 2023 (Akta No. 084/2023). Perusahaan berfokus pada bidang penjualan GPS Pelacak Kendaraan dan menyediakan layanan yang mencakup penjualan perangkat keras dan perangkat lunak untuk produk Internet of Things (IoT) transportasi darat, seperti gps tracker. Dengan konsumen utama dari berbagai sektor, termasuk perusahaan logistik, rental, pembiayaan, korporasi, dan individu yang ingin melacak kendaraan mereka, Perusahaan menjalankan layanan pelanggan 24 jam dengan dukungan teknis yang tersebar di berbagai kota di Indonesia. Fox Logger, sebagai solusi pelacakan yang inovatif, menjadi produk andalan perusahaan ini dengan kemampuan menerima data dari berbagai merek GPS Car Tracker dengan Call Center 24 jam. Dengan keunggulan kompetitif seperti sertifikasi internasional, kemampuan penyesuaian fitur, dan dukungan teknis yang handal, Perusahaan terus berkembang dalam industri pelacakan dan manajemen kendaraan.',
            ticker: 'BREN',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/BREN.webp',
            address: 'Wisma Barito Pacific II, Lantai 23, Jl. Let. Jend. S. Parman Kav. 60, RT 010, RW 005, Slipi, Palmerah, Jakarta 11410, Indonesia',
            bidang_usaha: 'Aktvitas Perusahaan Holding',
            website: 'https://www.baritorenewables.co.id/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=266&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=266&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=266',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/266/bren-pt-barito-renewables-energy-tbk',
            low_price: 670,
            high_price: 780,
            // final_price: 780,
            offered_shares: 4500000000,
            outstanding_shares: 134271220000,
            kurs_usd: 15062,
            kurs_date: new Date("2023-03-31"),
            date_awal_start: new Date("2023-09-18"),
            date_awal_end: new Date("2023-09-25"),
            date_umum_start: new Date("2023-10-02"),
            date_umum_end: new Date("2023-10-04"),
            date_penjatahan: new Date("2023-10-04"),
            date_distribusi: new Date("2023-10-05"),
            date_ipo: new Date("2023-10-06"),
            subsector_id: 7,
        },
    })
    await prisma.company.upsert({
        where: { id: 3 },
        update: {},
        create: {
            name: 'PT Sumber Sinergi Makmur Tbk',
            description: 'PT Sumber Sinergi Makmur, yang berkantor pusat di Jakarta Pusat, didirikan pada tanggal 19 Mei 2015 berdasarkan Akta Pendirian No. 88 yang dibuat di hadapan seorang notaris di Jakarta Pusat. Perusahaan ini memperoleh status badan hukum pada tanggal 28 Mei 2015 berdasarkan Surat Keputusan Menkumham No. AHU-2440801.01.01.Tahun 2015. Selama perjalanannya, Anggaran Dasar Perusahaan telah mengalami beberapa kali perubahan, yang terakhir terjadi pada tanggal 25 Mei 2023 (Akta No. 57/2023) dan tanggal 24 Juli 2023 (Akta No. 084/2023). Perusahaan berfokus pada bidang penjualan GPS Pelacak Kendaraan dan menyediakan layanan yang mencakup penjualan perangkat keras dan perangkat lunak untuk produk Internet of Things (IoT) transportasi darat, seperti gps tracker. Dengan konsumen utama dari berbagai sektor, termasuk perusahaan logistik, rental, pembiayaan, korporasi, dan individu yang ingin melacak kendaraan mereka, Perusahaan menjalankan layanan pelanggan 24 jam dengan dukungan teknis yang tersebar di berbagai kota di Indonesia. Fox Logger, sebagai solusi pelacakan yang inovatif, menjadi produk andalan perusahaan ini dengan kemampuan menerima data dari berbagai merek GPS Car Tracker dengan Call Center 24 jam. Dengan keunggulan kompetitif seperti sertifikasi internasional, kemampuan penyesuaian fitur, dan dukungan teknis yang handal, Perusahaan terus berkembang dalam industri pelacakan dan manajemen kendaraan.',
            ticker: 'IOTF',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/IOTF.webp',
            address: 'Fox Logger Tower Jl. Cideng Barat nomor 31A, RT. 003/RW. 011, Kelurahan Cideng, Kecamatan Gambir, Jakarta Pusat 10150',
            bidang_usaha: 'Distributor dan Instalasi Perangkat Global Positioning System (GPS) untuk Otomotif dan Logistik',
            website: 'https://www.foxlogger.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=265&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=265&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=265',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/265/iotf-pt-sumber-sinergi-makmur-tbk',
            low_price: 100,
            high_price: 120,
            // final_price: 100,
            offered_shares: 1100000000,
            outstanding_shares: 5280000000,
            waran_numerator: 1,
            waran_denominator: 1,
            exercise_price: 130,
            date_awal_start: new Date("2023-09-14"),
            date_awal_end: new Date("2023-09-19"),
            date_umum_start: new Date("2023-10-2"),
            date_umum_end: new Date("2023-10-5"),
            date_penjatahan: new Date("2023-10-5"),
            date_distribusi: new Date("2023-10-6"),
            date_ipo: new Date("2023-10-9"),
            subsector_id: 3,
        },
    })
    await prisma.company.upsert({
        where: { id: 4 },
        update: {},
        create: {
            name: 'PT Anugerah Spareparts Sejahtera Tbk',
            description: 'PT Anugerah Spareparts Sejahtera adalah perusahaan yang didirikan berdasarkan Akta Pendirian Perseroan Terbatas pada tanggal 10 September 2015 di Kota Cirebon. Mereka telah mendapatkan pengesahan resmi dari Menteri Hukum dan Hak Asasi Manusia Republik Indonesia. Sejak pendirian hingga saat ini, Anggaran Dasar perusahaan telah mengalami beberapa perubahan, yang terakhir dilakukan pada tanggal 28 April 2023. Perusahaan ini memiliki domisili di Kabupaten Cirebon dan kantor pusatnya berada di Jalan Soekarno Hatta Nomor 134. Mereka bergerak dalam industri suku cadang dan aksesori kendaraan bermotor roda empat atau lebih, perdagangan besar suku cadang dan aksesori mobil, serta perdagangan besar bahan konstruksi dari kayu. Saat ini, kegiatan utama perusahaan berfokus pada industri suku cadang dan aksesori kendaraan bermotor roda empat atau lebih serta perdagangan besar suku cadang dan aksesori mobil.',
            ticker: 'AEGS',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/AEGS.webp',
            address: 'Jalan Soekarno Hatta No. 134, Losari Kidul, Losari, Kab. Cirebon, Jawa Barat 45192',
            bidang_usaha: 'Industri Filter Kendaraan Bermotor yaitu Filter Oli dan Filter Bahan Bakar, serta Perdagangan Filter',
            website: 'https://www.aegisfilter.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=262&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=262&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=262',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/262/aegs-pt-anugerah-spareparts-sejahtera-tbk',
            low_price: 90,
            high_price: 100,
            // final_price: 100,
            offered_shares: 400000000,
            outstanding_shares: 1006000000,
            waran_numerator: 4,
            waran_denominator: 1,
            exercise_price: 90,
            date_awal_start: new Date("2023-08-22"),
            date_awal_end: new Date("2023-08-24"),
            date_umum_start: new Date("2023-09-04"),
            date_umum_end: new Date("2023-09-07"),
            date_penjatahan: new Date("2023-09-07"),
            date_distribusi: new Date("2023-09-08"),
            date_ipo: new Date("2023-09-11"),
            subsector_id: 4,
        },
    })
    await prisma.company.upsert({
        where: { id: 5 },
        update: {},
        create: {
            name: 'PT Kokoh Exa Nusantara Tbk',
            description: 'PT Kokoh Exa Nusantara adalah perusahaan di bidang konstruksi dan properti yang didirikan pada tahun 2019 di Kabupaten Bangkalan, Jawa Timur. Mereka fokus pada pengembangan proyek perumahan Kokoh City, dengan penjualan rumah subsidi untuk Masyarakat Berpenghasilan Rendah (MBR) dan rumah komersial konsep "Kota Mandiri." Kokoh City terletak sekitar 15 km dari pusat Surabaya dan merupakan bagian dari GERBANG KERTASUSILA, wilayah penyanggah Surabaya.\n' +
                '\n' +
                'Perusahaan ini memiliki dukungan teknologi pembuatan dinding rumah yang dipatenkan dari PT Kokoh Anugerah Nusantara, pemegang saham mereka. PT Kokoh Anugerah Nusantara telah berpengalaman di industri properti, real estat, dan konstruksi sejak 2015.\n' +
                '\n' +
                'PT Kokoh Exa Nusantara juga memiliki peran penting dalam penyaluran Fasilitas Likuiditas Pembiayaan Perumahan (FLPP) untuk rumah tapak MBR di Provinsi Jawa Timur, dan merupakan penyumbang terbesar di Kabupaten Bangkalan, Madura menurut BP Tapera pada tahun 2022.',
            ticker: 'KOCI',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/KOCI.webp',
            address: 'Jl. Raya Sukolilo, Tebul, Kwanyar, Bangkalan - 69163',
            bidang_usaha: 'Konstruksi dan Real Estat',
            website: 'https://www.kokohcity.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=264&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=264&type=summary',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/264/koci-pt-kokoh-exa-nusantara-tbk',
            low_price: 120,
            high_price: 160,
            // final_price: 120,
            offered_shares: 450000000,
            outstanding_shares: 4415590000,
            waran_numerator: 1,
            waran_denominator: 1,
            date_awal_start: new Date("2023-09-07"),
            date_awal_end: new Date("2023-09-12"),
            date_umum_start: new Date("2023-09-27"),
            date_umum_end: new Date("2023-10-04"),
            date_penjatahan: new Date("2023-10-05"),
            date_distribusi: new Date("2023-10-09"),
            date_ipo: new Date("2023-10-10"),
            subsector_id: 5,
        },
    })
    await prisma.company.upsert({
        where: { id: 6 },
        update: {},
        create: {
            name: 'PT Lovina Beach Brewery Tbk',
            description: 'PT Lovina Beach Brewery, sebuah perusahaan Indonesia yang telah berperan sebagai pelopor dalam industri craft beer di negara ini, memiliki fokus utama dalam distribusi minuman beralkohol. Perusahaan ini juga memiliki anak perusahaan yang terlibat dalam produksi minuman beralkohol, mulai dari tahap awal brewing hingga menghasilkan produk minuman beralkohol yang siap untuk didistribusikan. Bahan baku utama yang digunakan untuk produksi minuman beralkohol ini diimpor dari berbagai negara seperti Jerman, Belgia, dan negara lainnya. Perseroan bertekad untuk menghasilkan produk minuman beralkohol dengan kualitas tingkat internasional.\n' +
                '\n' +
                'Perusahaan mulai beroperasi dalam distribusi minuman beralkohol pada tahun 2010, saat itu fokus distribusi hanya pada produk dengan kadar alkohol golongan A (0% hingga 5%). Kemudian, pada tahun 2016, Perseroan mengembangkan usahanya dengan memasarkan produk minuman beralkohol golongan B (dengan kadar alkohol antara 5,01% hingga 20,00%) dan golongan C (dengan kadar alkohol antara 20,01% hingga 55,00%). Pada tahun 2020, Perseroan memperluas jangkauannya dengan mendistribusikan minuman beralkohol beraroma lokal.',
            ticker: 'STRK',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/STRK.webp',
            address: 'Jl. Tukad Banyu Poh 110 X, Sesetan Denpasar Selatan, 80223',
            bidang_usaha: 'Bergerak dalam bidang Industri Distribusi Minuman Beralkohol & Pengolahannya melalui Anak perusahaan',
            website: 'https://lovinabeachbrewery.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=263&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=263&type=summary',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/263/strk-pt-lovina-beach-brewery-tbk',
            low_price: 100,
            high_price: 119,
            // final_price: 100,
            offered_shares: 1180000000,
            outstanding_shares: 10721709000,
            waran_numerator: 100,
            waran_denominator: 275,
            exercise_price: 250,
            date_awal_start: new Date("2023-09-06"),
            date_awal_end: new Date("2023-09-20"),
            date_umum_start: new Date("2023-10-03"),
            date_umum_end: new Date("2023-10-06"),
            date_penjatahan: new Date("2023-10-06"),
            date_distribusi: new Date("2023-10-09"),
            date_ipo: new Date("2023-10-10"),
            subsector_id: 6,
        },
    })
    await prisma.company.upsert({
        where: { id: 7 },
        update: {},
        create: {
            name: 'PT Koka Indonesia Tbk',
            description: 'PT Koka Indonesia Tbk ("Perseroan") adalah sebuah perusahaan terbatas yang didirikan pada tahun 2011 dan berfokus pada sektor kontraktor umum dalam proyek konstruksi, teknik mesin, teknik geoteknik, desain interior, dan produksi furniture. Perusahaan ini memiliki tingkat kualifikasi yang tinggi dalam bidang konstruksi bangunan, konstruksi industri pabrik, serta jembatan dan terowongan, dan telah melaksanakan berbagai proyek investasi dan konstruksi di Indonesia. Dalam lebih dari 10 tahun beroperasi, Perseroan telah menyelesaikan lebih dari 100 proyek di Indonesia. Dalam menjalankan operasinya, Perseroan mengikuti standar ISO 9001, ISO 14001, dan OHSAS 18001 untuk sistem manajemen mutu, lingkungan, serta kesehatan dan keselamatan kerja.',
            ticker: 'KOKA',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/KOKA.webp',
            address: 'Jl. Sultan Iskandar Muda, No. 7, Lt. 3, Kebayoran Lama, Jakarta Selatan 12240',
            bidang_usaha: 'Jasa Konstruksi Gedung Industri, Bangunan Sipil dan Gedung Hunian',
            website: 'https://koka.co.id/en/beranda-en/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=267&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=267&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=267',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/267/koka-pt-koka-indonesia-tbk',
            low_price: 128,
            high_price: 161,
            // final_price: 128,
            offered_shares: 715333000,
            outstanding_shares: 2861333000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-09-19"),
            date_awal_end: new Date("2023-09-26"),
            date_umum_start: new Date("2023-10-02"),
            date_umum_end: new Date("2023-10-05"),
            date_penjatahan: new Date("2023-10-05"),
            date_distribusi: new Date("2023-10-06"),
            date_ipo: new Date("2023-10-09"),
            subsector_id: 8,
        },
    })
    await prisma.company.upsert({
        where: { id: 8 },
        update: {},
        create: {
            name: 'PT Logisticsplus International Tbk',
            description: 'PT Logisticsplus International Tbk adalah penyedia jasa transportasi, terletak di SAV Building, Jagakarsa, Jakarta Selatan. Berdiri sejak 2013, mulai beroperasi pada tahun 2016 dengan hanya 2 truk dan 3 pelanggan. Saat ini, mereka memiliki lebih dari 20 pelanggan dan armada yang lebih besar.\n' +
                '\n' +
                'PT Logisticsplus International Tbk merupakan hasil kerjasama antara pengusaha logistik lokal dan Logisticsplus Inc, yang memiliki jaringan internasional di hampir 180 negara. Mereka dapat memanfaatkan jaringan ini untuk pengiriman barang internasional. PT Logisticsplus International Tbk juga menawarkan layanan kepabeanan, pengemasan, penyimpanan, pemilahan barang, dan pelabelan.\n' +
                '\n' +
                'Selama bertahun-tahun, PT Logisticsplus International Tbk telah berpengalaman dalam mengirim berbagai jenis barang, termasuk alat kesehatan, peralatan pengeboran minyak, peralatan pemurnian minyak, alat telekomunikasi, alat transportasi kereta, makanan, dan pembangkit listrik, serta menyediakan layanan pengemasan, penyimpanan, dan dokumentasi bea cukai.',
            ticker: 'LOPI',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/LOPI.webp',
            address: 'SAV Building Jl. Kavling Polri No. 20 Jagakarsa, Jakarta Selatan 12620, Indonesia',
            bidang_usaha: 'Jasa Pengurusan Transportasi (Freight Forwarding)',
            website: 'https://www.logisticsplus.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=269&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=269&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=269',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/269/lopi-pt-logisticsplus-international-tbk',
            low_price: 100,
            high_price: 150,
            // final_price: 100,
            offered_shares: 300000000,
            outstanding_shares: 1100000000,
            waran_numerator: 2,
            waran_denominator: 1,
            exercise_price: 200,
            date_awal_start: new Date("2023-09-20"),
            date_awal_end: new Date("2023-09-22"),
            date_umum_start: new Date("2023-10-03"),
            date_umum_end: new Date("2023-10-05"),
            date_penjatahan: new Date("2023-10-05"),
            date_distribusi: new Date("2023-10-06"),
            date_ipo: new Date("2023-10-09"),
            subsector_id: 9,
        },
    })
    await prisma.company.upsert({
        where: { id: 9 },
        update: {},
        create: {
            name: 'PT Pulau Subur Tbk',
            description: 'PT Pulau Subur didirikan pada tahun 1980 dan memiliki lahan perkebunan Kelapa Sawit di dua lokasi, yaitu Desa Gelebak Dalam, Kecamatan Rambutan, Kabupaten Banyuasin dan Desa Sukadarma, Kecamatan Jejawi, Kabupaten Ogan Komering Ilir (OKI), Palembang, Sumatera Selatan. Pada awalnya, pada tahun 1981, perusahaan ini mulai beroperasi di bidang perkebunan karet, jagung, serta peternakan dan perikanan. Namun, karena meningkatnya permintaan terhadap Crude Palm Oil (CPO), pada tahun 2003, perusahaan memutuskan untuk mulai menanam bibit kelapa sawit di lahan seluas 12,5 hektar. Sejak itu, perusahaan telah fokus pada pengembangan perkebunan kelapa sawit, dengan total izin lokasi seluas 1.180,39 hektar dan total luas lahan sebesar 1.205,52 hektar, terdiri dari lahan berstatus Hak Guna Usaha (HGU) seluas 882,58 hektar dan Alih Fungsi Hutan (APH) seluas 322,94 hektar. Pada tahun 2022, produksi per hektar mencapai 30.059 ton Tandan Buah Segar (TBS). Secara rinci, luas lahan Tanaman Belum Menghasilkan (TBM) perusahaan adalah sekitar 94,89 hektar atau sekitar 8,70%, sementara luas lahan Tanaman Menghasilkan (TM) mencapai 995,75 hektar (94,89%).\n' +
                '\n' +
                'PT Pulau Subur Tbk beroperasi sesuai dengan peraturan perundang-undangan yang berlaku di Indonesia dan berkantor pusat di Palembang. Perusahaan ini didirikan melalui Akta Pendirian Perseroan Terbatas PT Pulau Subur No. 1 pada tanggal 1 Oktober 1980, yang dibuat di hadapan Notaris Justin AR., S.H., Notaris di Palembang. Akta ini telah mendapatkan pengesahan dari Menteri Kehakiman Republik Indonesia berdasarkan Surat Keputusan No. YA.5/13/21 tanggal 7 Juni 1982 dan terdaftar dalam buku daftar Kepaniteraan Pengadilan Negeri Palembang dengan nomor 46/1982 tanggal 7 Juli 1982. Selain itu, pendirian perusahaan juga diumumkan dalam Berita Negara Republik Indonesia No. 3728, Tambahan Berita Negara No. 50 tanggal 22 Juni 1999.',
            ticker: 'PTPS',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/PTPS.webp',
            address: 'Jl A. Yani No.12 ABC, RT23 RW023 14 Ulu, Seberang Ulu Dua, Palembang',
            bidang_usaha: 'Perseroan bergerak dalam bidang Perkebunan Buah Kelapa Sawit',
            website: 'https://www.pulausubur.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=268&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=268&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=268',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/268/ptps-pt-pulau-subur-tbk',
            low_price: 198,
            high_price: 206,
            // final_price: 198,
            offered_shares: 450000000,
            outstanding_shares: 2167500000,
            waran_numerator: 2,
            waran_denominator: 1,
            exercise_price: null,
            date_awal_start: new Date("2023-09-20"),
            date_awal_end: new Date("2023-09-22"),
            date_umum_start: new Date("2023-10-03"),
            date_umum_end: new Date("2023-10-05"),
            date_penjatahan: new Date("2023-10-05"),
            date_distribusi: new Date("2023-10-06"),
            date_ipo: new Date("2023-10-09"),
            subsector_id: 10,
        },
    })
    await prisma.company.upsert({
        where: { id: 10 },
        update: {},
        create: {
            name: 'PT Agro Bahari Nusantara Tbk',
            description: 'Perseroan ini berfokus pada bisnis budidaya Udang Vannamei (Litopenaeus Vannamei) dan telah mengalami pertumbuhan yang signifikan dalam usahanya. Awalnya, mereka hanya memiliki 6 kolam budidaya, tetapi sekarang mereka mengoperasikan 14 kolam yang intensif dan super-intensif. Sejak tahun 2019, Perseroan telah berhasil memproduksi lebih dari 400 ton udang Vannamei, baik untuk ekspor maupun pemenuhan kebutuhan dalam negeri. Dalam menjalankan operasinya, Perseroan sangat menekankan pendekatan ilmiah dan penggunaan analisis statistik. Dengan pendekatan ini, mereka mampu mengurangi risiko kegagalan panen akibat penyakit dan kondisi cuaca yang seringkali memengaruhi budidaya udang. Aset utama Perseroan saat ini mencakup 10 kolam budidaya udang intensif, 4 kolam super intensif, 3 kolam tendon, 4 Instalasi Pengolahan Air Limbah (IPAL), serta peralatan pendukung seperti aerator (kincir air), pompa, dan lainnya.',
            ticker: 'UDNG',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/UDNG.webp',
            address: 'Ruko Shibuya Unit SHC 012 – PIK 2 Jl. Marina Indah Raya No.1 Kel. Lemo, Kec. Teluknaga Tangerang – Banten 15510',
            bidang_usaha: 'Budidaya Tambak Udang',
            website: 'https://abn.farm/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=270&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=270&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=270',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/270/udng-pt-agro-bahari-nusantara-tbk',
            low_price: 90,
            high_price: 100,
            // final_price: 100,
            offered_shares: 500000000,
            outstanding_shares: 1750000000,
            waran_numerator: 5,
            waran_denominator: 4,
            exercise_price: 110,
            date_awal_start: new Date("2023-10-06"),
            date_awal_end: new Date("2023-10-12"),
            date_umum_start: new Date("2023-10-23"),
            date_umum_end: new Date("2023-10-26"),
            date_penjatahan: new Date("2023-10-26"),
            date_distribusi: new Date("2023-10-27"),
            date_ipo: new Date("2023-10-30"),
            subsector_id: 11,
        },
    })
    await prisma.company.upsert({
        where: { id: 11 },
        update: {},
        create: {
            name: 'PT Multitrend Indo Tbk',
            description: 'PT Multitrend Indo adalah perusahaan ritel yang berfokus pada penjualan fashion dan aksesoris untuk bayi dan remaja awal. Mereka memulai operasi pada tahun 2005 di bawah naungan PT Kanmo Retailindo, dengan gerai pertama dibuka di Mal Taman Anggrek. Sejak itu, mereka terus berkembang dengan membuka gerai-garai lainnya, memperkenalkan merek seperti Gingersnaps dan Justice, serta meluncurkan platform online mothercare.co.id pada tahun 2013. Kantor pusat perusahaan ini berlokasi di Jakarta, Indonesia, dan hingga Juni 2023, mereka telah mengoperasikan 128 gerai di seluruh Indonesia. Bisnis Perseroan mencakup ritel offline dengan lisensi eksklusif merek global untuk bayi dan anak-anak, ritel online, dan distribusi produk prinsipal serta produk mereka sendiri melalui anak perusahaannya, PT Kanmo Multi Gemilang (KMG), yang menghadirkan berbagai merek terkenal seperti Banz, HEAD, J&J, MICRO, NUBY, Playgro, TY Brand, YAMATOYA, ZOGGS, dan PT Actavis Indonesia.',
            ticker: 'BABY',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/BABY.webp',
            address: 'Gedung Menara Era Lt. 14-02 Jl. Senen Raya No. 135 – 137, Kel. Senen, Kec. Senen, Jakarta Pusat, Provinsi DKI Jakarta, 10410',
            bidang_usaha: 'Perdagangan Eceran Pakaian dan Mainan Anak',
            website: 'https://kanmomultitrend.id/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=261&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=261&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=261',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/261/baby-pt-multitrend-indo-tbk',
            low_price: 250,
            high_price: 266,
            // final_price: 266,
            offered_shares: 534000000,
            outstanding_shares: 2668586400,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-08-14"),
            date_awal_end: new Date("2023-08-22"),
            date_umum_start: new Date("2023-08-31"),
            date_umum_end: new Date("2023-09-05"),
            date_penjatahan: new Date("2023-09-05"),
            date_distribusi: new Date("2023-09-06"),
            date_ipo: new Date("2023-09-07"),
            subsector_id: 12,
        },
    })
    await prisma.company.upsert({
        where: { id: 12 },
        update: {},
        create: {
            name: 'PT Charlie Hospital Semarang Tbk',
            description: 'PT Charlie Hospital Semarang Tbk, adalah sebuah entitas hukum yang beroperasi di Kabupaten Kendal, Jawa Tengah, Indonesia. Perseroan didirikan dan beroperasi sesuai dengan hukum dan peraturan Indonesia, terutama Undang-Undang Perseroan Terbatas. Saat ini, Perseroan berlokasi di Ngabean, Kelurahan Ngabean, Kecamatan Boja, Kabupaten Kendal, Jawa Tengah, dan memulai kegiatan komersialnya pada tahun 2019. Perseroan resmi terbentuk dengan nama PT Charlie Hospital Semarang pada tahun 2019, berdasarkan Akta Pendirian Nomor 35 tanggal 11 Februari 2019 yang disahkan oleh Menteri Hukum dan Hak Asasi Manusia Republik Indonesia pada tanggal 16 Februari 2019. Perseroan juga terdaftar dengan nomor Tanda Daftar Perusahaan No. AHU-0026304.AH.01.11.TAHUN pada tanggal yang sama dan telah diumumkan dalam Berita Negara pada tanggal 16 Desember 2022.',
            ticker: 'RSCH',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/RSCH.webp',
            address: 'Jl. Raya Ngabean Kav 1A, Kel. Ngabean, Kec. Boja Kab. Kendal, Jawa Tengah 51381',
            bidang_usaha: 'Rumah Sakit Swasta',
            website: 'https://charliehospital.co.id/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=260&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=260&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=260',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/260/rsch-pt-charlie-hospital-semarang-tbk',
            low_price: 105,
            high_price: 125,
            // final_price: 115,
            offered_shares: 530000000,
            outstanding_shares: 2650000000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-08-04"),
            date_awal_end: new Date("2023-08-08"),
            date_umum_start: new Date("2023-08-22"),
            date_umum_end: new Date("2023-08-24"),
            date_penjatahan: new Date("2023-08-24"),
            date_distribusi: new Date("2023-08-25"),
            date_ipo: new Date("2023-08-28"),
            subsector_id: 13,
        },
    })
    await prisma.company.upsert({
        where: { id: 13 },
        update: {},
        create: {
            name: 'PT Kian Santang Muliatama Tbk',
            description: 'PT Kian Santang Muliatama Tbk, yang berkedudukan di Bekasi dan didirikan pada tanggal 28 November 2018, adalah perusahaan yang fokus pada penyediaan layanan penting untuk industri gas, mulai dari pasokan suku cadang hingga layanan rekayasa, pengadaan, dan konstruksi (EPC). Berbasis di Bekasi, Jawa Barat, KSM telah beroperasi sejak tahun 2018 di bawah manajemen individu yang berpengalaman di sektor minyak dan gas, terutama dalam infrastruktur gas. Perusahaan ini berkomitmen pada visi dan misi yang telah ditetapkan, yang mencerminkan aspirasi para pendiri. Kegiatan utama perusahaan dibagi menjadi dua segmen: penjualan produk, termasuk regulator, fitting transisi, dan kit konverter, di samping segmen jasa yang mencakup layanan konstruksi seperti pembangunan stasiun pengukuran dan regulasi gas, sektor regulator, dan layanan terkait lainnya. Saat ini, perusahaan aktif dalam perdagangan besar mesin, peralatan, dan perlengkapan lainnya, serta layanan instalasi mekanikal dan minyak dan gas.',
            ticker: 'RGAS',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/RGAS.webp',
            address: 'Jl. Wibawa Mukti II Perum Telkom Satwika Permai Blok A5 No. 8, RT. 009 RW. 009 Kel. Jatiluhur, Kec. Jatiasih, Bekasi, 17425',
            bidang_usaha: 'Perdagangan Besar Mesin Peralatan & Perlengkapan Lainnya, Instalasi Mekanikal dan Instalasi Gas',
            website: 'https://kianmulia.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=272&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=272&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=272',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/272/rgas-pt-kian-santang-muliatama-tbk',
            low_price: 115,
            high_price: 122,
            // final_price: 120,
            offered_shares: 334200000,
            outstanding_shares: 1459200000,
            waran_numerator: 5,
            waran_denominator: 3,
            exercise_price: 210,
            date_awal_start: new Date("2023-10-16"),
            date_awal_end: new Date("2023-10-18"),
            date_umum_start: new Date("2023-11-02"),
            date_umum_end: new Date("2023-11-06"),
            date_penjatahan: new Date("2023-11-06"),
            date_distribusi: new Date("2023-11-07"),
            date_ipo: new Date("2023-11-08"),
            subsector_id: 14,
        },
    })
    await prisma.company.upsert({
        where: { id: 14 },
        update: {},
        create: {
            name: 'PT Ikapharmindo Putramas Tbk',
            description: 'PT. Ikapharmindo Putramas, yang bermula sebagai apotik, berdiri sejak 18 Mei 1978 dengan pabrik utamanya di Kawasan Pulogadung seluas 11,700 m2. Saat ini, fasilitas produksinya telah berkembang termasuk produksi, laboratorium riset dan pengembangan (R&D), kontrol kualitas, pergudangan, dan kantor pusat. Fasilitas tersebut memenuhi standar GMP dari BPOM dan didukung oleh teknologi SAP untuk memastikan produk-produk farmasi dan perawatan personal berkualitas. Mereka juga membuka pabrik kedua di Jawa Barat pada 2016, khusus untuk produk perawatan bayi Baby Huki. Dengan visi menjadi perusahaan farmasi dan perawatan personal yang profesional, inovatif, dan berorientasi pada kesehatan, Perseroan akan memperluas fasilitas di Jawa Barat untuk pasar internasional, terutama produk perawatan rambut, tetap berfokus pada inovasi dan kualitas, serta menyediakan produk untuk berbagai generasi dengan portofolio yang berkembang.',
            ticker: 'IKPM',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/IKPM.webp',
            address: 'Kl. Pulogadung Raya No.29 Kawasan Industri Pulogadung Jakarta Timur, 13930 Indonesia',
            bidang_usaha: 'Industri Farmasi, Personal Care',
            website: 'https://www.ikapharmindo.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=274&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=274&type=summary',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/274/ikpm-pt-ikapharmindo-putramas-tbk',
            low_price: 160,
            high_price: 180,
            // final_price: 165,
            offered_shares: 336932500,
            outstanding_shares: 1684662500,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-10-23"),
            date_awal_end: new Date("2023-10-30"),
            date_umum_start: new Date("2023-11-02"),
            date_umum_end: new Date("2023-11-06"),
            date_penjatahan: new Date("2023-11-08"),
            date_distribusi: new Date("2023-11-09"),
            date_ipo: new Date("2023-11-10"),
            subsector_id: 15,
        },
    })
    await prisma.company.upsert({
        where: { id: 15 },
        update: {},
        create: {
            name: 'PT Mastersystem Infotama Tbk',
            description: 'PT Mastersystem Infotama Tbk adalah penyedia layanan system integration yang telah beroperasi selama lebih dari 29 tahun di Indonesia. Mereka mengintegrasikan berbagai komponen perangkat keras, perangkat lunak, jaringan, dan komunikasi dalam solusi Information and Communication Technology (ICT) yang komprehensif, memungkinkan kolaborasi antara sistem teknologi yang beragam. Mereka menawarkan solusi inovatif seperti data center, cloud infrastructure, kolaborasi perusahaan, manajemen bisnis digital, big data, dan keamanan adaptif. Perseroan adalah salah satu penyedia solusi IT terbesar di Indonesia dengan pangsa pasar sebesar 6,9% pada tahun 2022. Mereka juga menyediakan layanan terkelola, termasuk solusi cloud, purna jual, dan pemeliharaan sistem IT. Sebagai mitra prinsipal global dan platform cloud ternama, Perseroan telah membangun data center on-premise dan mengembangkan teknologi enterprise networking dan collaboration sendiri.',
            ticker: 'MSTI',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/MSTI.webp',
            address: 'Gedung Sudirman 7-8 Tower I Lt.25 Jl. Jend. Sudirman Kav. 7-8 Jakarta Pusat 10220',
            bidang_usaha: 'Solusi, Integrasi dan Pemeliharaan Sistem Teknologi Informasi',
            website: 'https://www.mastersystem.co.id/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=271&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=271&type=summary',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/271/msti-pt-mastersystem-infotama-tbk',
            low_price: 1355,
            high_price: 1595,
            // final_price: 1355,
            offered_shares: 667000000,
            outstanding_shares: 3335000000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-10-20"),
            date_awal_end: new Date("2023-10-26"),
            date_umum_start: new Date("2023-11-02"),
            date_umum_end: new Date("2023-11-06"),
            date_penjatahan: new Date("2023-11-06"),
            date_distribusi: new Date("2023-11-07"),
            date_ipo: new Date("2023-11-08"),
            subsector_id: 16,
        },
    })
    await prisma.company.upsert({
        where: { id: 16 },
        update: {},
        create: {
            name: 'PT Janu Putra Sejahtera Tbk',
            description: 'PT Janu Putra Sejahtera Tbk. ("Perseroan") bergerak dalam kegiatan peternakan ayam dan rumah potong ayam. Produk dan jasa yang ditawarkan oleh Perseroan meliputi DOC Parent Stock, DOC Ayam Broiler, Ayam Hidup, Karkas Ayam, Telur Komersil, dan Layanan Rumah Potong Ayam. Saat ini, Perseroan memiliki dua lokasi kandang breeding Parent Stock yang terletak di Ngawis dan Purbalingga, sementara peternakan Ayam Broiler berada di Klerong dan Sleman.',
            ticker: 'AYAM',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/AYAM.webp',
            address: 'Ruko Casa Grande No.35, Jl. Ringroad Utara, Maguwoharjo, Depok, Sleman, D.I Yogyakarta ',
            bidang_usaha: 'Bergerak Dalam Bidang Usaha Peternakan Dan Rumah Potong Ayam ',
            website: 'https://januputrasejahtera.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=275&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=275',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=275',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/275/ayam-pt-janu-putra-sejahtera-tbk',
            low_price: 100,
            high_price: 110,
            // final_price: 100,
            offered_shares: 800000000,
            outstanding_shares: 4000000000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-11-10"),
            date_awal_end: new Date("2023-11-16"),
            date_umum_start: new Date("2023-11-24"),
            date_umum_end: new Date("2023-11-28"),
            date_penjatahan: new Date("2023-11-28"),
            date_distribusi: new Date("2023-11-29"),
            date_ipo: new Date("2023-11-30"),
            subsector_id: 11,
        },
    })
    await prisma.company.upsert({
        where: { id: 17 },
        update: {},
        create: {
            name: 'PT Maja Agung Latexindo Tbk',
            description: 'PT Maja Agung Latexindo, yang berkedudukan di Kabupaten Deli Serdang, didirikan pada 25 Oktober 1988 dengan nama PT Maja Agung Latexindo. Pembentukan perusahaan ini teregistrasi dalam Akta Perseroan Terbatas PT Maja Agung Latexindo No. 283, dibuat di hadapan Benny Kristianto, S.H., seorang Notaris di Jakarta, dan mendapat pengesahan Menkumham No. C2-10064.HT.01.01.TH.1989. Perusahaan, yang memiliki visi menjadi produsen sarung tangan terbaik dunia, telah mengubah Anggaran Dasar beberapa kali sejak pendiriannya, dengan perubahan terakhir tercatat dalam Akta No. 12/2023. Misi Perseroan adalah menjadi perusahaan manufaktur berkelanjutan yang menyediakan produk berkualitas tinggi berdasarkan kebutuhan pelanggan dan kepatuhan terhadap standar dunia. Dengan keunggulan kompetitif seperti tim manajemen yang handal, mutu produk berstandar internasional, sinergi grup, operasional yang mendukung kebijakan ESG pemerintah, dan struktur biaya efisien, Perseroan memiliki prospek yang cerah. Industri sarung tangan lateks terus berkembang, didorong oleh permintaan global dalam sektor medis, makanan, dan industri lainnya. Dalam konteks ini, pandemi COVID-19 telah memberikan dampak positif pada pasar sarung tangan lateks, terutama pada segmen pemeriksaan dan penggunaan sekali pakai. (Sumber: www.gminsights.com)',
            ticker: 'SURI',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/SURI.webp',
            address: 'Jalan Utama No 98 Desa Pujimulyo, Kecamatan Sunggal, Kabupaten Deli Serdang, Sumatera Utara 20352',
            bidang_usaha: 'Bergerak Dalam Bidang Produsen Sarung Tangan Latex',
            website: 'https://www.malgloves.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=276&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=276&type=summary',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/276/suri-pt-maja-agung-latexindo-tbk',
            low_price: 160,
            high_price: 170,
            // final_price: 170,
            offered_shares: 1266875000,
            outstanding_shares: 6334375000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-11-13"),
            date_awal_end: new Date("2023-11-15"),
            date_umum_start: new Date("2023-12-01"),
            date_umum_end: new Date("2023-12-05"),
            date_penjatahan: new Date("2023-12-05"),
            date_distribusi: new Date("2023-12-06"),
            date_ipo: new Date("2023-12-07"),
            subsector_id: 17,
        },
    })
    await prisma.company.upsert({
        where: { id: 18 },
        update: {},
        create: {
            name: 'PT Asri Karya Lestari Tbk',
            description: 'PT Asri Karya Lestari, sebuah perusahaan kontraktor nasional di Indonesia, telah menorehkan pengalaman selama 15 tahun dalam proyek pembangunan, termasuk pekerjaan pondasi, erection, bekisting, dan konstruksi jalan. Dengan penerapan ilmu pengetahuan dan teknologi yang terus berkembang, perusahaan telah terlibat dalam berbagai proyek strategis nasional dan swasta. Untuk memperluas dampaknya dalam pembangunan nasional, PT Asri Karya Lestari mengembangkan sub-bisnis dengan mengakuisisi PT Bumi Prima Kontruksi, fokus pada persewaan alat berat dan konstruksi bangunan sipil, serta PT Manyar Perkasa Mandiri yang bergerak dalam industri batching plant. Dengan langkah ini, perusahaan dapat mengoptimalkan peluang bisnis dari hulu sampai ke hilir, menciptakan perputaran usaha yang lebih menyeluruh.',
            ticker: 'ASLI',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/ASLI.webp',
            address: 'Ruko Sentra Niaga Kalimalang B2 No3 Jl. Jend. Ahmad Yani, Bekasi, Jawa Barat 17144',
            bidang_usaha: 'General Contractor (Ppekerjaan Pondasi, Erection, Bekisting)',
            website: 'https://www.asrikaryalestari.co.id/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=277&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=277&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=277',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/277/asli-pt-asri-karya-lestari-tbk',
            low_price: 100,
            high_price: 130,
            // final_price: null,
            offered_shares: 1250000000,
            outstanding_shares: 6250000000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-12-12"),
            date_awal_end: new Date("2023-12-18"),
            date_umum_start: new Date("2023-12-29"),
            date_umum_end: new Date("2024-01-03"),
            date_penjatahan: new Date("2024-01-03"),
            date_distribusi: new Date("2024-01-04"),
            date_ipo: new Date("2024-01-05"),
            subsector_id: 8,
        },
    })
    await prisma.company.upsert({
        where: { id: 19 },
        update: {},
        create: {
            name: 'PT Manggung Polahraya Tbk',
            description: 'PT Manggung Polahraya Tbk, didirikan pada tahun 1992, awalnya berfokus pada Jasa Konstruksi dan Pengadaan. Namun, seiring berjalannya waktu, perusahaan ini berkembang menjadi pemain utama dalam Jasa Konstruksi Gedung, Pembangunan Infrastruktur Jalan, dan produksi Aspal Hot Mix serta Beton Ready Mix. Dengan pengalaman lebih dari 30 tahun, PT Manggung Polahraya Tbk telah berhasil menyelesaikan berbagai proyek strategis baik dari pemerintah, Badan Usaha Milik Negara/Daerah, maupun swasta. Pencapaian ini tidak hanya memberikan kepuasan kepada pelanggan tetapi juga memungkinkan perusahaan untuk bertahan dan berkembang. Selama perjalanannya, beberapa proyek penting seperti Rehabilitasi dan Rekonstruksi Bangunan Gedung BPKP Perwakilan Provinsi Sulawesi Tengah, Renovasi Menara Siger Bakauheni Lampung, dan Pembuatan Reservoir Tank Bandara Kualanamu telah berhasil diselesaikan. PT Manggung Polahraya Tbk juga memiliki pabrik beton untuk memproduksi berbagai mutu beton ready mix dan pabrik aspal (Aspal Mixing Plant/AMP) dengan jangkauan pemasaran yang meliputi beberapa Kotamadya/Kabupaten di sekitar Bandar Lampung.',
            ticker: 'MANG',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/MANG.webp',
            address: 'Jl. Pondok Pinang Raya No.1, Kebayoran Lama, Jakarta Selatan, DKI Jakarta 12310',
            bidang_usaha: 'Jasa Konstruksi Gedung, Pembangunan Infrastruktur Jalan, Produksi Aspal Hot Mix & Beton Ready Mix',
            website: 'https://www.manggungpolahraya.co.id/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=278&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=278&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=278',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/278/mang-pt-manggung-polahraya-tbk',
            low_price: 90,
            high_price: 110,
            // final_price: null,
            offered_shares: 762500000,
            outstanding_shares: 3812500000,
            waran_numerator: 10,
            waran_denominator: 3,
            exercise_price: 125,
            date_awal_start: new Date("2023-12-14"),
            date_awal_end: new Date("2023-12-18"),
            date_umum_start: new Date("2024-01-03"),
            date_umum_end: new Date("2024-01-09"),
            date_penjatahan: new Date("2024-01-09"),
            date_distribusi: new Date("2024-01-10"),
            date_ipo: new Date("2024-01-11"),
            subsector_id: 8,
        },
    })
    await prisma.company.upsert({
        where: { id: 20 },
        update: {},
        create: {
            name: 'PT Citra Nusantara Gemilang Tbk',
            description: 'PT Citra Nusantara Gemilang, yang didirikan di Kabupaten Bekasi berdasarkan hukum negara Republik Indonesia pada tanggal 21 Desember 2005 dan mengalami perubahan melalui akta perubahan tanggal 11 September 2006, merupakan perusahaan yang diakui sebagai pelopor dalam pengembangan gas alam terkompresi (Compressed Natural Gas / CNG) di Indonesia. Fokus utamanya adalah perdagangan dan distribusi gas alam ke daerah-daerah yang belum terjangkau oleh jaringan pipa gas dengan tekanan gas yang stabil dan aman. Selain melayani sektor industri, transportasi, dan perumahan, perusahaan juga menyediakan jasa konsultasi terkait operasional dan perawatan peralatan gas alam. PT Citra Nusantara Gemilang merupakan induk dari beberapa anak perusahaan seperti PT Citra Nusantara Energi, PT CNG Hilir Raya, PT CNG Global, dan PT Cipta Rizqi Energi, yang masing-masing memiliki peran dalam distribusi, perdagangan, dan konstruksi gas alam. Dengan jaringan distribusi yang telah menjangkau berbagai daerah di Indonesia, perusahaan berencana untuk memperluas layanannya dengan mengembangkan bisnis perdagangan dan distribusi Liquefied Natural Gas (LNG) selain CNG.',
            ticker: 'CGAS',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/CGAS.webp',
            address: 'Jl. Kalimalang No.126, Tegal Gede, Kelurahan Pasirsari, Kecamatan Cikarang Selatan, Kabupaten Bekasi, Provinsi Jawa Barat 17530 Indonesia',
            bidang_usaha: 'Perdagangan & Distribusi Gas Alam',
            website: 'https://cng.co.id/',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=280&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=280&type=summary',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/280/cgas-pt-citra-nusantara-gemilang-tbk',
            low_price: 284,
            high_price: 338,
            // final_price: null,
            offered_shares: 531429000,
            outstanding_shares: 1771429000,
            waran_numerator: 2,
            waran_denominator: 1,
            exercise_price: 306,
            date_awal_start: new Date("2023-12-14"),
            date_awal_end: new Date("2023-12-19"),
            date_umum_start: new Date("2024-01-02"),
            date_umum_end: new Date("2024-01-04"),
            date_penjatahan: new Date("2024-01-04"),
            date_distribusi: new Date("2024-01-05"),
            date_ipo: new Date("2024-01-08"),
            subsector_id: 18,
        },
    })
    await prisma.company.upsert({
        where: { id: 21 },
        update: {},
        create: {
            name: 'PT Adhi Kartiko Pratama Tbk',
            description: 'PT Adhi Kartiko Pratama Tbk, didirikan pada 2008, adalah perusahaan pertambangan nikel yang fokus pada ekstraksi bijih nikel melalui proyek eksplorasi nikel laterit di Desa Lameruru, Konawe Utara, Sulawesi Tenggara, Indonesia. Dengan luas area konsesi 1.975 hektar, perusahaan sepenuhnya memiliki dan mengoperasikan tambangnya. Terletak dekat pantai dengan jarak 600 meter dari dermaga, perusahaan menekankan efisiensi operasional. Akses mudah dari Kendari dalam lima jam perjalanan memperkuat kemudahan operasional. Dengan fokus pada keberlanjutan, keselamatan, dan inovasi, perusahaan berkomitmen menyediakan bijih nikel berkualitas tinggi, dengan dampak positif pada masyarakat setempat. Dengan dedikasi terhadap standar keselamatan tinggi, perusahaan mengatributkan kesuksesannya pada kerja keras dan komitmen karyawan. Operasional sesuai dengan regulasi ketat, menciptakan lingkungan kerja aman, bermanfaat, dan inovatif, menjaga posisi perusahaan sebagai pemimpin industri.',
            ticker: 'NICE',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/NICE.webp',
            address: 'Jalan Sorumba Nomor 80, Desa/Kelurahan Anaiwoi, Kec. Kadia, Kota Kendari, Provinsi Sulawesi Tenggara Indonesia - 93118',
            bidang_usaha: 'Bergerak dalam Pertambangan Bijih Nikel',
            website: 'https://www.akp.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/en/pipeline/get-propectus-file?id=281&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/en/pipeline/get-propectus-file?id=281&type=summary',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/en/ipo/281/nice-pt-adhi-kartiko-pratama-tbk',
            low_price: 430,
            high_price: 530,
            // final_price: null,
            offered_shares: 1216404000,
            outstanding_shares: 6082020000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            date_awal_start: new Date("2023-12-15"),
            date_awal_end: new Date("2023-12-21"),
            date_umum_start: new Date("2024-01-03"),
            date_umum_end: new Date("2024-01-05"),
            date_penjatahan: new Date("2024-01-05"),
            date_distribusi: new Date("2024-01-06"),
            date_ipo: new Date("2024-01-09"),
            subsector_id: 19,
        },
    })
    await prisma.company.upsert({
        where: { id: 22 },
        update: {},
        create: {
            name: 'PT Sinergi Multi Lestarindo Tbk',
            description: 'PT Sinergi Multi Lestarindo, didirikan pada 2013, beroperasi di sektor perdagangan, pengangkutan darat, percetakan, perindustrian, jasa, pembangunan, bengkel, dan pertanian. Sebagai penyedia solusi satu atap untuk industri makanan & minuman, perawatan diri, dan bahan kimia industri di Indonesia, perusahaan berfokus pada perdagangan bahan kimia khusus untuk bahan baku makanan & minuman, bahan baku perawatan diri, dan bahan baku kimia industri. Mereka juga melakukan formulasi khusus, menyediakan produk berkualitas seperti oleoresin, ekstrak, flavor, dehydrated product, pengawet, pewarna makanan, anti-oksidan, pengemulsi, nutraceuticals, natural oil, filter UV, rheology modifier, asam lemak, texturizer, dan bahan fungsional lainnya. Produk mereka digunakan dalam berbagai industri termasuk pengolahan makanan, minuman, toiletries, kesehatan, suplemen, personal care, dan kosmetik. Pendapatan diperoleh melalui penjualan bahan kimia khusus dengan model distribusi yang mencakup R&D, tim penjualan berkompetensi, layanan pelanggan, dan dukungan teknis. Model perdagangan mereka melibatkan platform penjualan langsung melalui kanal seperti Instagram, YouTube, LinkedIn, atau situs web perusahaan, membedakan mereka dengan inovasi dan layanan teknis yang memperkuat posisi di pasar.',
            ticker: 'SMLE',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/SMLE.webp',
            address: 'Business Park Kebon Jeruk Blok I 5-6, Jl. Raya Meruya Illir, Kav.88, Meruya Utara, Kembangan, Jakarta Barat 11620',
            bidang_usaha: 'Perdagangan Bahan Kimia Khusus untuk Bahan Baku Makanan & Minuman, Perawatan Diri dan Kimia Industri',
            website: 'https://www.ptsml.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=283&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=283&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=283',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/283/smle-pt-sinergi-multi-lestarindo-tbk',
            low_price: 175,
            high_price: 190,
            // final_price: null,
            offered_shares: 465625000,
            outstanding_shares: 2328125000,
            waran_numerator: 2,
            waran_denominator: 1,
            exercise_price: 210,
            date_awal_start: new Date("2023-12-15"),
            date_awal_end: new Date("2023-12-22"),
            date_umum_start: new Date("2024-01-02"),
            date_umum_end: new Date("2024-01-08"),
            date_penjatahan: new Date("2024-01-08"),
            date_distribusi: new Date("2024-01-09"),
            date_ipo: new Date("2024-01-10"),
            subsector_id: 20,
        },
    })
    await prisma.company.upsert({
        where: { id: 23 },
        update: {},
        create: {
            name: 'PT Samcro Hyosung Adilestari Tbk',
            description: 'PT Samcro Hyosung Adilestari beroperasi di sektor industri dan perdagangan, menghasilkan berbagai produk seperti perekat Hook dan Loop/Magic Tape atau Pita Pengait rekat dan webbing tape. Produk ini berfungsi sebagai pengganti kancing dan resleting, memberikan kemudahan dan kenyamanan dalam berbagai aplikasi produksi seperti manufaktur boneka, pakaian, alas kaki, peralatan olahraga, alat kesehatan, kemasan, konstruksi, aksesories, otomotif, dan alat tulis. Dengan sistem yang ramah lingkungan dan aman, perusahaan ini membantu mengurangi limbah di lokasi pabrik sambil meningkatkan efisiensi waktu pemasangan dan kebutuhan alat, sehingga proses manufaktur dapat dilakukan lebih cepat dan terjangkau.',
            ticker: 'ACRO',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/ACRO.webp',
            address: 'Jl. Raya Serang KM 17,2 Desa Bojong Kecamatan Cikupa, Kabupaten Tangerang Banten, 15710',
            bidang_usaha: 'Bergerak dalam industri dan perdagangan Hook dan Loop',
            website: 'https://www.samcro.co.id',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=282&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=282&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=282',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/282/acro-pt-samcro-hyosung-adilestari-tbk',
            low_price: 103,
            high_price: 108,
            // final_price: null,
            offered_shares: 693828000,
            outstanding_shares: 3469138591,
            waran_numerator: 3,
            waran_denominator: 1,
            exercise_price: 186,
            date_awal_start: new Date("2023-12-15"),
            date_awal_end: new Date("2023-12-22"),
            date_umum_start: new Date("2024-01-02"),
            date_umum_end: new Date("2024-01-08"),
            date_penjatahan: new Date("2024-01-08"),
            date_distribusi: new Date("2024-01-09"),
            date_ipo: new Date("2024-01-10"),
            subsector_id: 21,
        },
    })
    await prisma.company.upsert({
        where: { id: 24 },
        update: {},
        create: {
            name: 'PT Multi Spunindo Jaya Tbk',
            description: 'PT Multi Spunindo Jaya Tbk berfokus pada kegiatan usaha utama di bidang Industri nonwoven secara business to business (B2B), memproduksi produk nonwoven Sheet yang digunakan sebagai bahan baku di berbagai sektor, mulai dari kesehatan (pembalut, popok, masker) hingga konstruksi dan agrikultur. Dengan standar tinggi bertaraf internasional, produk nonwoven yang dihasilkan dapat didistribusikan ke pasar nasional dan internasional. Perseroan memiliki laboratorium penelitian In-house Research and Development (R&D) dengan sistem Total Quality Management (TQM) untuk memenuhi permintaan spesifik pasar. Dengan lahan produksi seluas ±150.000 meter persegi, Perseroan dan Perusahaan Anak beroperasi dengan lebih dari 700 pekerja, menggunakan sistem rotasi 4 kelompok untuk menjaga lini produksi berjalan selama 24 jam non-stop. Saat ini, Perseroan memiliki 12 lini produksi, termasuk 9 lini produksi dengan teknologi Spunbond dan Spunmelt, 3 lini produksi dengan teknologi Meltblown, dan 1 lini produksi dengan teknologi Needlepunch.',
            ticker: 'MSJA',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/MSJA.webp',
            address: 'Desa Jabaran, Kecamatan Balongbendo, Krian, Sidoarjo, Jawa Timur, Indonesia 61263',
            bidang_usaha: 'Industri Nonwoven',
            website: 'https://www.spunindo.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=284&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=284&type=summary',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/284/msja-pt-multi-spunindo-jaya-tbk',
            low_price: 250,
            high_price: 350,
            // final_price: null,
            offered_shares: 882352900,
            outstanding_shares: 5882352900,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            kurs_usd: 15407,
            kurs_date: new Date("2023-11-30"),
            date_awal_start: new Date("2023-12-18"),
            date_awal_end: new Date("2023-12-21"),
            date_umum_start: new Date("2024-01-03"),
            date_umum_end: new Date("2024-01-08"),
            date_penjatahan: new Date("2024-01-08"),
            date_distribusi: new Date("2024-01-09"),
            date_ipo: new Date("2024-01-10"),
            subsector_id: 22,
        },
    })
    await prisma.company.upsert({
        where: { id: 25 },
        update: {},
        create: {
            name: 'PT Griptha Putra Persada Tbk',
            description: 'PT Griptha Putra Persada, didirikan pada tahun 2010 dan berlokasi di Kota Kudus, Jawa Tengah, awalnya berfokus pada industri perhotelan, restoran, dan layanan MICE dengan nama Hotel Griptha. Meskipun didirikan pada 2010, operasional perusahaan baru dimulai pada tahun 2015, saat ini mengoperasikan 138 kamar hotel dengan berbagai fasilitas termasuk ruang pertemuan, ballroom, tempat ibadah, kolam renang, dan pusat kebugaran. Visi perusahaan adalah menjadi perusahaan perhotelan yang profesional, terus berkembang, dan berorientasi pada kepuasan pengunjung. Misi mereka melibatkan memberikan pelayanan terbaik kepada pengunjung, selalu berinovasi dalam layanan, produk, dan pengembangan SDM, serta berorientasi pada peningkatan nilai perusahaan dan memberikan manfaat sosial. Moto perusahaan adalah "Growing with Hospitality," mencerminkan semangat pertumbuhan bersama dengan penuh keramahan dalam setiap aspek bisnisnya.',
            ticker: 'GRPH',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/GRPH.webp',
            address: 'Jl. AKBP R. Agil Kusumadya No. 100, Jati Wetan, Kecamatan Jati, Kabupaten Kudus, Jawa Tengah 59346, Indonesia',
            bidang_usaha: 'Hotel Bintang, Restoran, dan MICE',
            website: 'https://www.griptha.com',
            prospectus_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=285&type=',
            prospectus_summary_url: 'https://www.e-ipo.co.id/id/pipeline/get-propectus-file?id=285&type=summary',
            additional_information_url: 'https://www.e-ipo.co.id/id/pipeline/get-additional-info?id=285',
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/285/grph-pt-griptha-putra-persada-tbk',
            low_price: 100,
            high_price: 105,
            // final_price: null,
            offered_shares: 200000000,
            outstanding_shares: 1000000000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2023-12-20"),
            date_awal_end: new Date("2023-12-28"),
            date_umum_start: new Date("2024-01-12"),
            date_umum_end: new Date("2024-01-16"),
            date_penjatahan: new Date("2024-01-16"),
            date_distribusi: new Date("2024-01-17"),
            date_ipo: new Date("2024-01-18"),
            subsector_id: 23,
        },
    })
    await prisma.company.upsert({
        where: { id: 26 },
        update: {},
        create: {
            name: 'PT Sumber Mineral Global Abadi Tbk',
            description: 'PT Sumber Mineral Global Abadi didirikan pada tahun 2016 dan berbasis di Jakarta Selatan. Fokus utama perusahaan adalah perdagangan nikel dan batubara untuk pasar domestik di Indonesia. Sebagai bagian dari kelompok usaha PT Sumber Global Energy Tbk (SGE), perusahaan ini terlibat dalam perdagangan batubara di pasar ekspor dan domestik dengan sistem pemasok batubara yang terintegrasi. Perusahaan memegang tiga IUP – OPK untuk pengangkutan dan penjualan mineral logam, batubara, dan mineral bukan logam. Saat ini, perusahaan lebih berorientasi pada nikel dan batubara berkualitas tinggi, memposisikannya sebagai trader dengan segmentasi pasar khusus. Kolaborasi dengan pemilik IUP-OP dan IUP-OPK memastikan kelangsungan produktivitas dan pasokan. Perusahaan juga terlibat tidak langsung dalam pertambangan batu gamping melalui investasinya di PT Jasatama Mandiri Sukses (JMS), yang telah memperoleh IUP untuk eksplorasi dan produksi batu gamping di Sulawesi Tengah. JMS memiliki cadangan batu gamping sekitar 300.000.000 ton dengan perkiraan usia tambang sekitar 150 tahun.',
            ticker: 'SMGA',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/SMGA.webp',
            address: 'Graha BIP Lantai 2, Jl. Gatot Subroto Kav. 23, Jakarta Selatan 12930, Indonesia',
            bidang_usaha: 'Perdagangan Besar Bijih Nikel dan Batubara',
            website: 'https://www.smgagroup.com',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/SMGA-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/SMGA-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/286/smga-pt-sumber-mineral-global-abadi-tbk',
            low_price: 100,
            high_price: 105,
            // final_price: null,
            offered_shares: 1750000000,
            outstanding_shares: 8750000000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-08"),
            date_awal_end: new Date("2024-01-11"),
            date_umum_start: new Date("2024-01-22"),
            date_umum_end: new Date("2024-01-25"),
            date_penjatahan: new Date("2024-01-25"),
            date_distribusi: new Date("2024-01-26"),
            date_ipo: new Date("2024-01-29"),
            subsector_id: 19,
        },
    })
    await prisma.company.upsert({
        where: { id: 27 },
        update: {},
        create: {
            name: 'PT Terang Dunia Internusa Tbk',
            description: 'Sejak tahun 1991, PT Terang Dunia Internusa telah menjadi perusahaan manufaktur sepeda Indonesia yang mendistribusikan lebih dari 300 jenis sepeda, 20 model sepeda listrik, dan empat variasi motor listrik di bawah merek terkenal, United. Produk-produk United menawarkan beragam varian sepeda, meliputi sepeda gunung, sepeda jalan, BMX, sepeda lipat, serta sepeda touring dan anak-anak, dipasarkan melalui jaringan 600 dealer di seluruh Indonesia dan luar negeri. Semua produk kami memiliki harga yang kompetitif, berkualitas tinggi, terjamin, dan didukung oleh jaringan penjualan nasional yang handal serta layanan purna jual yang responsif. PT Terang Dunia Internusa memiliki pengalaman luas dalam membangun merek United, yang kini menduduki posisi utama di pasar sepeda. Perusahaan ini berkomitmen untuk terus beradaptasi dengan teknologi terkini guna memenuhi kebutuhan para pengendara sepeda dan tetap relevan dengan tren sepeda. Untuk mencapai hal ini, PT Terang Dunia Internusa berkomitmen pada inovasi sambil tetap menjaga kualitas dan relevansi produk mereka. Selanjutnya, PT Terang Dunia Internusa mendukung aspirasi global menuju masa depan berkelanjutan dengan mengembangkan sepeda listrik dan motor listrik yang ramah lingkungan sebagai alternatif untuk motor berbasis mesin pembakaran dalam (internal combustion engine/ICE). Upaya ini direalisasikan melalui peningkatan investasi dalam penelitian dan pengembangan, pemasaran, infrastruktur, dan implementasi strategi end-to-end.',
            ticker: 'UNTD',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/UNTD.webp',
            address: 'Jl. Alam Sutera Boulevard No. kav. 12A, Pakulonan, Kec. Serpong utara, Kota Tangerang Selatan, Banten 15325',
            bidang_usaha: 'Industri Sepeda dan Industri Sepeda Motor Roda Dua dan Tiga',
            website: 'https://www.terangduniainternusa.com',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/UNTD-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/UNTD-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/287/untd-pt-terang-dunia-internusa-tbk',
            low_price: 170,
            high_price: 240,
            // final_price: null,
            offered_shares: 1666666700,
            outstanding_shares: 6666666700,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-11"),
            date_awal_end: new Date("2024-01-22"),
            date_umum_start: new Date("2024-02-01"),
            date_umum_end: new Date("2024-02-05"),
            date_penjatahan: new Date("2024-02-05"),
            date_distribusi: new Date("2024-02-06"),
            date_ipo: new Date("2024-02-07"),
            subsector_id: 24,
        },
    })
    await prisma.company.upsert({
        where: { id: 28 },
        update: {},
        create: {
            name: 'PT Topindo Solusi Komunika Tbk',
            description: 'Topindo Solusi Komunika Tbk, sebuah start-up yang berdiri sejak 2018, awalnya merupakan pengembangan dari platform Top Pulsa yang didirikan oleh Bapak Seiko Manito pada tahun 2009, berfokus pada penjualan pulsa. Pada 2018, mereka merilis aplikasi TopindoPay untuk memberikan peluang usaha dengan modal minim. Dari 2019 hingga 2021, TopindoPay terus berkembang dengan fitur produk virtual dan FMCG yang dijual secara online, serta peluncuran aplikasi Android dan iOS. Pada 2022, mereka melakukan rebranding menjadi Topindoku. Melalui Topindoku, mereka menawarkan produk virtual seperti pulsa, paket data, voucher game, dan layanan pembayaran lainnya, terutama untuk UMKM seperti warung dan kedai. Dengan lebih dari 995.000 pengunduh di Playstore, 23.500 di App Store, 25 gerai, dan 66 Top Up Point pada tahun 2023, Topindoku menjadi kekuatan dalam memberdayakan UMKM di Indonesia, berbasis di Kota Singkawang dengan operasional mayoritas di wilayah Kalimantan.',
            ticker: 'TOSK',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/TOSK.webp',
            address: 'Jalan P. Diponegoro No. 19, Kel. Pasiran, Kec Singkawang Barat, Kota Singkawang, Prov Kalimantan Barat 79123',
            bidang_usaha: 'Platform Teknologi untuk Tujuan Komersil',
            website: 'https://topindoku.co.id/',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/TOSK-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/TOSK-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/288/tosk-pt-topindo-solusi-komunika-tbk',
            low_price: 115,
            high_price: 125,
            // final_price: null,
            offered_shares: 875000000,
            outstanding_shares: 4375000000,
            waran_numerator: 10,
            waran_denominator: 3,
            exercise_price: 156,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-15"),
            date_awal_end: new Date("2024-01-19"),
            date_umum_start: new Date("2024-01-29"),
            date_umum_end: new Date("2024-02-01"),
            date_penjatahan: new Date("2024-02-01"),
            date_distribusi: new Date("2024-02-02"),
            date_ipo: new Date("2024-02-05"),
            subsector_id: 25,
        },
    })
    await prisma.company.upsert({
        where: { id: 29 },
        update: {},
        create: {
            name: 'PT Ancara Logistics Indonesia Tbk',
            description: 'PT Ancara Logistics Indonesia Tbk didirikan pada bulan Juli 2019 dan beroperasi di sektor jasa pengangkutan laut, transshipment, dan Intermediate Stockpile (ISP) untuk tambang batu bara. Dengan sistem logistik terintegrasi, Ancara Logistics memiliki saham mayoritas di PT Mahakam Coal Terminal (MCT), yang berfungsi sebagai ISP. Melalui kontrak Life of Mine (LoM) dengan PT Ade Putra Tanrajeng (APT) dan PT Guruh Putra Bersama (GPB), perusahaan memastikan pendapatan berkelanjutan hingga habisnya cadangan batu bara. Ancara Logistics memiliki armada besar termasuk kapal tunda dan tongkang, lokasi ISP strategis, teknologi pelacakan kapal online, dan fokus pada kesehatan, keselamatan, dan lingkungan memberikan keunggulan kompetitif. Visi Ancara Logistics adalah menjadi penyedia layanan terdepan dalam logistik dan jasa pertambangan, sedangkan misinya adalah menyediakan solusi unggul dengan memperhatikan keselamatan dan lingkungan. Keberlanjutan pertumbuhan nilai bagi pemegang saham dijaga dengan manajemen yang berpengalaman di industri pengangkutan laut dan komitmen terhadap Kesehatan, Keselamatan, dan Lingkungan.',
            ticker: 'ALII',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/ALII.webp',
            address: 'Bakrie Tower Lantai 15, Komplek Rasuna Epicentrum, Jalan H.R. Rasuna Said, Kelurahan Karet Kuningan, Kecamatan Setiabudi, Kota Administrasi Jakarta Selatan, 12940',
            bidang_usaha: 'Jasa Pengangkutan Laut dan Transshipment, serta Intermediate Stockpile melalui Perusahaan Anak',
            website: 'https://www.ancaralogistics.co.id',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/ALII-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/ALII-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/289/alii-pt-ancara-logistics-indonesia-tbk',
            low_price: 268,
            high_price: 278,
            // final_price: null,
            offered_shares: 3165160000,
            outstanding_shares: 15825800000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-17"),
            date_awal_end: new Date("2024-01-24"),
            date_umum_start: new Date("2024-02-01"),
            date_umum_end: new Date("2024-02-05"),
            date_penjatahan: new Date("2024-02-05"),
            date_distribusi: new Date("2024-02-06"),
            date_ipo: new Date("2024-02-07"),
            subsector_id: 26,
        },
    })
    await prisma.company.upsert({
        where: { id: 30 },
        update: {},
        create: {
            name: 'PT Mitra Pedagang Indonesia Tbk',
            description: 'PT Mitra Pedagang Indonesia Tbk, didirikan pada tahun 2019 di Kota Bangkalan, Madura, Indonesia, berperan sebagai penyedia solusi pembayaran dan transaksi digital untuk pelaku UMKM. Melalui platform "MPStore SuperApp UMKM," Perseroan menawarkan beragam produk dan layanan, termasuk Agregator Produk Digital, Layanan QRIS Merchant, Kasir Online Gratis, Street Banking/MINI ATM, E-commerce & E-grocery (Kulakan), Agen Logistik, Akses Permodalan (Kredit Usaha Rakyat), hingga Quick commerce mini web. Dengan fokus pada pengembangan bisnis UMKM, MPStore menyediakan solusi menyeluruh untuk produk, pembayaran, manajemen, dan pengiriman. Visi Perseroan adalah menjadikan MPStore sebagai aplikasi utama bagi pelaku UMKM dalam menjalankan bisnis sehari-hari, serta berperan dalam mendigitalisasi dan menskala-up UMKM di Indonesia.',
            ticker: 'MPIX',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/MPIX.webp',
            address: 'Ruko Khayangan Residence Blok RA-11, Lantai 2, Jalan Halim Perdana Kusuma, Bangkalan 69119, Jawa Timur',
            bidang_usaha: 'Penyedia Platform Digital untuk UMKM, dan E-Commerce',
            website: 'https://www.mpstore.co.id',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/MPIX-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/MPIX-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/290/mpix-pt-mitra-pedagang-indonesia-tbk',
            low_price: 256,
            high_price: 268,
            // final_price: null,
            offered_shares: 312500000,
            outstanding_shares: 1562500000,
            waran_numerator: 2,
            waran_denominator: 1,
            exercise_price: 850,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-17"),
            date_awal_end: new Date("2024-01-24"),
            date_umum_start: new Date("2024-01-31"),
            date_umum_end: new Date("2024-02-02"),
            date_penjatahan: new Date("2024-02-02"),
            date_distribusi: new Date("2024-02-05"),
            date_ipo: new Date("2024-02-06"),
            subsector_id: 25,
        },
    })
    await prisma.company.upsert({
        where: { id: 31 },
        update: {},
        create: {
            name: 'PT Multikarya Asia Pasifik Raya Tbk',
            description: 'Pada tahun 1998, Mud King didirikan di Amerika Serikat dan berfokus di wilayah Asia Pasifik (ASPAC) melalui PT Mud King Asia Pasifik Raya sejak 2002. Mereka menyediakan suku cadang dan jasa sewa alat berat untuk industri minyak dan gas di Indonesia. Mulai tahun 2005, ekspansi dilakukan ke penyewaan pompa melalui PT Petrodrill Manufaktur Indonesia, yang kemudian dilepas pada tahun 2023. PT Mudking Asia Pasifik Raya juga pionir dalam pekerjaan jasa sewa Water Transfer & Brine Pump untuk proyek Geotermal di Indonesia pada 2008. Pada tahun 2012, Perseroan berganti nama menjadi PT Multikarya Asia Pasifik Raya dan menjadi distributor tunggal produk Double Life Corp. USA di Indonesia. Ekspansi ke Reengineering & Refurbishment Mudpump dilakukan pada 2014. Dalam beberapa tahun terakhir, Perseroan berhasil mendapatkan kontrak proyek migas dari perusahaan terkemuka dan memperoleh hak keagenan baru untuk Pumpworks 610 (2020) dan brand WEG (2023). Kantor pusat Perseroan berada di Jakarta Selatan, dengan workshop di Jakarta, Sumatera Selatan, dan Jawa Barat, termasuk workshop utama di Citeurup yang diresmikan pada tahun 2023.',
            ticker: 'MKAP',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/MKAP.webp',
            address: 'Cibis Nine lt 16, JL TB Simatupang No 02, Jakarta Selatan, 12560, Indonesia',
            bidang_usaha: 'Manufaktur, Jasa Perdagangan, Penyewaan, Perbaikan, Suku Cadang Pompa Industri Migas & Pertambangan',
            website: 'https://www.mkapr.co.id/',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/MKAP-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/MKAP-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/291/mkap-pt-multikarya-asia-pasifik-raya-tbk',
            low_price: 105,
            high_price: 120,
            // final_price: null,
            offered_shares: 650000000,
            outstanding_shares: 3250000000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-18"),
            date_awal_end: new Date("2024-01-25"),
            date_umum_start: new Date("2024-02-01"),
            date_umum_end: new Date("2024-02-06"),
            date_penjatahan: new Date("2024-02-06"),
            date_distribusi: new Date("2024-02-07"),
            date_ipo: new Date("2024-02-12"),
            subsector_id: 14,
        },
    })
    await prisma.company.upsert({
        where: { id: 32 },
        update: {},
        create: {
            name: 'PT Harta Djaya Karya Tbk',
            description: 'Pada awal pendirian, PT Harta Djaya Karya Tbk beroperasi di bidang pembangunan, termasuk sebagai pemborong pekerjaan bangunan, penyedia jasa konsultan desain interior, dan perdagangan furnitur pada tahun 2012. Dengan workshop di Sawangan, perusahaan secara bertahap memperkuat legalitas, sertifikasi keahlian, dan struktur modalnya. Kesempatan menjadi vendor di Instansi Pemerintah dan kemitraan dengan perusahaan swasta terkemuka, seperti Bank Mandiri, Trinusa Travelindo, Goodyear Indonesia, dan British School Jakarta, menjadi landasan bagi perkembangan pesatnya. Pada tahun 2021, PT Harta Djaya Karya Tbk terpilih sebagai kontraktor dalam Proyek Revitalisasi Taman Ismail Marzuki, dan pada tahun berikutnya, mendapatkan proyek interior untuk BUMN seperti Bank Mandiri dan Adhi Karya, serta proyek Moda Raya Terpadu (MRT) Jakarta. Dalam lebih dari 10 tahun beroperasi, PT Harta Djaya Karya Tbk telah menjadi perusahaan jasa desain yang terpercaya dengan rekam jejak klien bergengsi dan pencapaian nilai kontrak tertinggi dalam 3 tahun terakhir. Saat ini, perusahaan berfokus pada 3 segmen bisnis: konsultasi desain, pelaksanaan konstruksi interior, dan pabrikasi furnitur.',
            ticker: 'MEJA',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/MEJA.webp',
            address: 'Jl. Bintaro Raya No.8A, Kby. Lama Selatan, Kec. Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta. Kode Pos: 12240',
            bidang_usaha: 'Konsultansi Desain, Pelaksana Konstruksi Interior, dan Pabrikasi Furnitur',
            website: 'https://interra.co.id/',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/MEJA-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/MEJA-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/292/meja-pt-harta-djaya-karya-tbk',
            low_price: 100,
            high_price: 103,
            // final_price: null,
            offered_shares: 480000000,
            outstanding_shares: 1917500000,
            waran_numerator: 1,
            waran_denominator: 1,
            exercise_price: 125,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-18"),
            date_awal_end: new Date("2024-01-24"),
            date_umum_start: new Date("2024-01-31"),
            date_umum_end: new Date("2024-02-05"),
            date_penjatahan: new Date("2024-02-05"),
            date_distribusi: new Date("2024-02-06"),
            date_ipo: new Date("2024-02-07"),
            subsector_id: 27,
        },
    })
    await prisma.company.upsert({
        where: { id: 33 },
        update: {},
        create: {
            name: 'PT Ecocare Indo Pasifik Tbk',
            description: 'PT Ecocare Indo Pasifik, sebelumnya dikenal sebagai PT Indocare Pacific yang didirikan pada tahun 2007, beroperasi di bidang Hygiene Support Services dengan tujuan melindungi lingkungan hidup dari virus dan bakteri. Dengan tim berpengalaman lebih dari 30 tahun di industri tersebut, perusahaan ini fokus pada kebersihan, kehigienisan, dan kenyamanan dengan komitmen untuk menyediakan pelayanan terbaik dan produk inovatif berbahan alami.\n' +
                '\n' +
                'Pada tahun 2017, ecoCare memperluas portofolionya dengan mendirikan TukangBersih (PT Tukang Bersih Indonesia), dan pada tahun 2021, mereka memperkenalkan pestCare sebagai solusi penanganan hama. Pada tahun 2023, PT Indocare Pacific mengubah namanya menjadi PT Ecocare Indo Pasifik.\n' +
                '\n' +
                'Sebagai bagian dari ecoCare Group Company, ecoCare, TukangBersih, dan pestCare berkolaborasi untuk menyediakan one-stop-solution dalam proteksi lingkungan di Indonesia. Visi perusahaan adalah meningkatkan citra perusahaan lokal Indonesia agar setara, disegani, dan dapat bersaing dengan perusahaan internasional di bidang Facilities Support Services. Misi perusahaan mencakup menjadi solusi lengkap dan terpercaya di bidang tersebut, memberikan prioritas kepada kepuasaan pelanggan, mengembangkan dan menjaga kesejahteraan karyawan, serta mendukung program "think green" dengan konsep layanan ramah lingkungan.',
            ticker: 'HYGN',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/HYGN.webp',
            address: 'Gedung Infinia Park, Jl. Dr. Saharjo No. 45 Blok A No. 55, Manggarai, Tebet, Jakarta Selatan 12850',
            bidang_usaha: 'Pengelolaan dan Penyewaan Alat-Alat Higienitas dan Sanitasi Ruangan',
            website: 'https://interra.co.id/',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/HYGN-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/HYGN-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/294/hygn-pt-ecocare-indo-pasifik-tbk',
            low_price: 135,
            high_price: 145,
            // final_price: null,
            offered_shares: 525000000,
            outstanding_shares: 2525000000,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-19"),
            date_awal_end: new Date("2024-01-24"),
            date_umum_start: new Date("2024-02-01"),
            date_umum_end: new Date("2024-02-05"),
            date_penjatahan: new Date("2024-02-05"),
            date_distribusi: new Date("2024-02-06"),
            date_ipo: new Date("2024-02-07"),
            subsector_id: 28,
        },
    })
    await prisma.company.upsert({
        where: { id: 34 },
        update: {},
        create: {
            name: 'PT Homeco Victoria Makmur Tbk',
            description: 'PT Homeco Victoria Makmur Tbk, didirikan pada tahun 2012, merupakan pemimpin pasar di Indonesia yang menawarkan berbagai kategori produk. Fokus utama perusahaan adalah perdagangan besar peralatan dan perlengkapan rumah tangga, alat tulis, alat permainan anak-anak, dan tekstil. Selain itu, sebagai perusahaan holding, PT Homeco Victoria Makmur Tbk mengelola entitas anak, PT Trisinar Indopratama (“TSI”), yang bergerak di industri barang plastik dengan merk “Technoplast”. Dengan pengalaman bisnis TSI selama 24 tahun, produk-produk berkualitas tinggi menjadi bagian dari komitmen perusahaan. PT Homeco Victoria Makmur Tbk berkomitmen untuk menyediakan produk berkualitas melalui distribusi yang efisien, mencakup lebih dari 40.000 titik penjualan di seluruh Indonesia. Dengan fokus kuat pada kualitas, kepercayaan, dan layanan pelanggan yang luar biasa, perusahaan berlokasi di Jakarta Barat, Indonesia, dengan tujuan memperluas jaringan distribusinya untuk memberikan kenyamanan dan kebahagiaan kepada setiap keluarga di Indonesia.',
            ticker: 'LIVE',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/LIVE.webp',
            address: 'Jl. Kebon Jeruk Raya No. 1A-C, Kel. Kebon Jeruk Kec. Kebon Jeruk, Kota Adm. Jakarta Barat Provinsi DKI Jakarta, 11530, Indonesia',
            bidang_usaha: 'Perdagangan Besar Peralatan dan Perlengkapan Rumah Tangga',
            website: 'http://www.homeco.co.id',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/LIVE-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/LIVE-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/293/live-pt-homeco-victoria-makmur-tbk',
            low_price: 136,
            high_price: 181,
            // final_price: null,
            offered_shares: 808350000,
            outstanding_shares: 4593005014,
            waran_numerator: null,
            waran_denominator: null,
            exercise_price: null,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-19"),
            date_awal_end: new Date("2024-01-24"),
            date_umum_start: new Date("2024-02-02"),
            date_umum_end: new Date("2024-02-06"),
            date_penjatahan: new Date("2024-02-06"),
            date_distribusi: new Date("2024-02-07"),
            date_ipo: new Date("2024-02-12"),
            subsector_id: 29,
        },
    })
    await prisma.company.upsert({
        where: { id: 35 },
        update: {},
        create: {
            name: 'PT Bersama Mencapai Puncak Tbk',
            description: 'PT Bersama Mencapai Puncak adalah perusahaan yang mengelola rumah makan dan terlibat dalam perdagangan bahan baku seperti makanan beku dan sembako. Perusahaan ini mengoperasikan langsung, melalui entitas anak, kemitraan rumah makan, serta perdagangan bahan baku. Dengan dua merek usaha makanan dan minuman, Ayam Goreng Nelongso (milik Perseroan) dan Geprek Kak Rose (milik Entitas Anak), perusahaan telah memiliki 64 outlet dan kemitraan yang tersebar di seluruh Indonesia. Ayam Goreng Nelongso, beroperasi sejak tahun 2013, menawarkan berbagai varian menu, sementara Geprek Kak Rose, berfokus pada penjualan ayam dan bebek, telah beroperasi sejak tahun 2017. Dengan cabang dan mitra yang dimulai di kota Malang, Jawa Timur, Perseroan kini memiliki jangkauan bisnis yang melibatkan Jabodebek, Jawa Barat, Jawa Tengah, dan Jawa Timur. Selain itu, perusahaan juga mengembangkan bisnis food supply untuk membantu masyarakat memulai bisnis dengan kemitraan, termasuk jual beli bahan baku segar seperti sembako, cabai, dan ayam. Total konsumen mencapai rata-rata 1,9 juta per tahun.',
            ticker: 'BAIK',
            img: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/img/BAIK.webp',
            address: 'Jl. Raya Regency Kav. 9 No. 5, Kabupaten Malang, Jawa Timur, 65153.',
            bidang_usaha: 'Mengelola Rumah Makan, Kemitraan Rumah Makan, serta Perdagangan Bahan Baku',
            website: 'https://ptbersamamencapaipuncak.com',
            prospectus_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/BAIK-P.pdf',
            prospectus_summary_url: 'https://juju.sgp1.cdn.digitaloceanspaces.com/indoipo/file/BAIK-PR.pdf',
            additional_information_url: null,
            e_ipo_url: 'https://www.e-ipo.co.id/id/ipo/295/baik-pt-bersama-mencapai-puncak-tbk',
            low_price: 268,
            high_price: 278,
            // final_price: null,
            offered_shares: 225000000,
            outstanding_shares: 1125000000,
            waran_numerator: 1,
            waran_denominator: 1,
            exercise_price: 400,
            kurs_usd: null,
            kurs_date: null,
            date_awal_start: new Date("2024-01-19"),
            date_awal_end: new Date("2024-01-24"),
            date_umum_start: new Date("2024-02-02"),
            date_umum_end: new Date("2024-02-12"),
            date_penjatahan: new Date("2024-02-12"),
            date_distribusi: new Date("2024-02-13"),
            date_ipo: new Date("2024-02-15"),
            subsector_id: 30,
        },
    })
}

module.exports = { seedCompanies }